---
title: "myddosome_proteomics"
author: "Finn"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r, warning = FALSE, message = FALSE, echo = FALSE}
pacman::p_load(tidyverse,data.table,jsonlite,janitor,ggrepel,UniprotR,knitr,svglite,readxl,plotly,fs,stringr,purrr, ggalt)

################################################################################
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE, fig.height=7, fig.width=14)
options(stringsAsFactors = FALSE)
theme_set(theme_bw())
theme_update(panel.grid.minor = element_blank())
################################################################################

source(file = ifelse(exists("https://raw.githubusercontent.com/tlobnow/myddosome_proteomics/main/scripts/functions.R"), 
                     yes =  "https://raw.githubusercontent.com/tlobnow/myddosome_proteomics/main/scripts/functions.R",
                     no  =  "~/Documents/Github/myddosome_proteomics/scripts/functions.R"))

FILES_LOC  = "~/Documents/Github/master_thesis/"

TIME_CHECK = fread(paste0(FILES_LOC, "summaries/TIME_CHECK.csv")) %>% 
  mutate(BAIT = case_when(KO == "NONE" ~ PULLED_PROTEIN,                                     
                          KO != "NONE" ~ paste(PULLED_PROTEIN, "KO", KO, sep = " ")))
TIME_CHECK$ORIGIN <- as.factor(TIME_CHECK$ORIGIN)

# QUERY_RUN_SUMMARY <- fread("~/Documents/Github/myddosome_proteomics/data/summaries/MYD88_summary_withRecycles.csv") %>% select(-V1) 
QUERY_RUN_SUMMARY <- fread("/Volumes/TAYLOR-LAB/Finn/CURATED_RESULTS/SUMMARIES/RECYCLES/MYD88_summaryWithRecycles.csv") %>%
  separate(FILE, into = c("FILE","rep"), sep = "_rep", extra = "merge", remove = T) %>%
  mutate(rep = as.numeric(rep))

QUERY_RUN_SUMMARY$MODEL <- sapply(strsplit(QUERY_RUN_SUMMARY$RECYCLE, "_"), function(x) x[2])

QUERY_RUN_SUMMARY$QUERY <- unlist(lapply(strsplit(QUERY_RUN_SUMMARY$FILE, "_", fixed=TRUE), function(x) {
  if ("MYD88" %in% x && "MOUSE" %in% x) {
    return(x[4])
  } else if ("MYD88" %in% x) {
    return(x[2])
  } else {
    return(x[4])
  }
}))

# Retain unique rows based on 'RECYCLE' column
QUERY_RUN_SUMMARY <- QUERY_RUN_SUMMARY %>% distinct(RECYCLE, .keep_all = TRUE)
QUERY_RUN_SUMMARY$DATE <- sapply(strsplit(QUERY_RUN_SUMMARY$RECYCLE, "_"), function(x) x[6])
QUERY_RUN_SUMMARY$DATE <- lubridate::as_date(QUERY_RUN_SUMMARY$DATE)

# Retain run ID from recycle
# QUERY_RUN_SUMMARY$RUN_ID <- sapply(strsplit(QUERY_RUN_SUMMARY$RECYCLE, "_"), function(x) x[7])

model_counts <- QUERY_RUN_SUMMARY %>%
  group_by(QUERY, MODEL) %>%
  filter(!str_detect(RECYCLE, "_recycled_")) %>%
  summarise(n = n()) %>%
  mutate(max_n = max(n)) %>%
  pivot_wider(id_cols = c(QUERY, max_n), names_from = MODEL, values_from = n)

# model_counts2 <- QUERY_RUN_SUMMARY %>%
#   group_by(QUERY, MODEL, DATE) %>%
#   filter(!str_detect(RECYCLE, "_recycled_")) %>%
#   summarise(n = n()) %>%
#   mutate(max_n = max(n)) #%>% pivot_wider(id_cols = c(QUERY, DATE, max_n), names_from = MODEL, values_from = n)
# 
# # Step 1: Create a "time block" for every 5 days
# model_counts2 <- model_counts2 %>%
#   mutate(DATE = as.Date(DATE)) %>%  # Convert to standard Date type
#   arrange(QUERY, DATE) %>%
#   group_by(QUERY) %>%
#   mutate(time_block = cumsum(c(TRUE, diff(DATE) > 5)))

# # Step 2: Group by QUERY and time_block
# model_counts_grouped <- model_counts2 %>%
#   group_by(QUERY, time_block) %>%
#   summarise(
#     min_date = min(DATE),
#     max_date = max(DATE),
#     total_models = sum(max_n, na.rm = TRUE))

# # Step 2: Count the appearance of each model within each time block for each QUERY
# model_counts2 <- model_counts2 %>%
#   group_by(QUERY, time_block, MODEL) %>%
#   mutate(model_count = row_number()) %>%
#   ungroup()

# Step 3: Assign a replicate number to each group
# model_counts_grouped <- model_counts_grouped %>%
#   mutate(replicate = row_number())

```

### Pulled Proteins

```{r}
unq_protein_ids          <- TIME_CHECK %>% pull(Protein.IDs) %>% unique() %>% as.data.frame()
unq_protein_ids_filtered <- unq_protein_ids %>% filter(!str_detect(., pattern = "CON__"))
unq_protein_ids_filtered <- unlist(lapply(strsplit(unq_protein_ids_filtered$., ";", fixed=TRUE), function(x) return(x[1]))) %>%
  unique() %>% as.data.frame()

# ========= Get the column containing unique protein IDs ===================== #
all_protein_ids <- unique(unq_protein_ids_filtered$.) %>% as.data.frame()
fwrite(all_protein_ids, "~/Documents/Github/myddosome_proteomics/data/summaries/all_protein_ids.csv", sep = ",", row.names = F, col.names = F, append = F)
```

### Add annotations for pulled proteins

```{r}
# === GO TERMS =============================================================== #
# fetch_data <- function(id) {
#   retries <- 3
#   while (retries > 0) {
#     tryCatch({
#       data <- UniprotR::GetProteinGOInfo(id)
#       return(data)
#     }, error = function(e) {
#       retries <<- retries - 1
#       if (retries == 0) {
#         message("Failed after 3 retries")
#         return(NULL)
#       } else {
#         message("Retrying...")
#         Sys.sleep(5)
#       }
#     })
#   }
# }
# GO_info_list        <- map(all_protein_ids, ~ fetch_data(.))
# GO_info_df          <- tibble(protein_id = all_protein_ids, GO_info = GO_info_list)
# GO_info_df_unnested <- GO_info_df %>% unnest(GO_info)

# === PROTEIN FUNCTIONS ====================================================== #
# fetch_data <- function(id) {
#   retries <- 3
#   while (retries > 0) {
#     tryCatch({
#       data <- UniprotR::GetProteinFunction(id)
#       return(data)
#     }, error = function(e) {
#       retries <<- retries - 1
#       if (retries == 0) {
#         message("Failed after 3 retries")
#         return(NULL)
#       } else {
#         message("Retrying...")
#         Sys.sleep(5)
#       }
#     })
#   }
# }
# proteinFCT_info_list        <- map(all_protein_ids, ~ fetch_data(.))
# proteinFCT_info_df          <- tibble(protein_id = all_protein_ids, proteinFCT_info = proteinFCT_info_list)
# proteinFCT_info_df_unnested <- proteinFCT_info_df %>% unnest(proteinFCT_info)

# === PROTEIN NAMES & TAXA =================================================== #
# fetch_data <- function(id) {
#   retries <- 3
#   while (retries > 0) {
#     tryCatch({
#       data <- UniprotR::GetNamesTaxa(id)
#       return(data)
#     }, error = function(e) {
#       retries <<- retries - 1
#       if (retries == 0) {
#         message("Failed after 3 retries")
#         return(NULL)
#       } else {
#         message("Retrying...")
#         Sys.sleep(5)  # Wait for 5 seconds before retrying
#       }
#     })
#   }
# }
# proteinNMS_info_list        <- map(all_protein_ids, ~ fetch_data(.))
# proteinNMS_info_df          <- tibble(protein_id = all_protein_ids, proteinNMS_info = proteinNMS_info_list)
# proteinNMS_info_df_unnested <- proteinNMS_info_df %>% unnest(proteinNMS_info)
#
# === JOIN THE DATA FRAMES AND SAVE ========================================== #
# unq_protein_ids_filtered <- rename(unq_protein_ids_filtered, protein_id = `.`)
# PROTEIN_INFO_1 <- full_join(unq_protein_ids_filtered, proteinNMS_info_df_unnested, by = "protein_id")
# PROTEIN_INFO_2 <- full_join(PROTEIN_INFO_1, proteinFCT_info_df_unnested,           by = "protein_id")
# PROTEIN_INFO_3 <- full_join(PROTEIN_INFO_2, GO_info_df_unnested,                   by = "protein_id")
# fwrite(PROTEIN_INFO_3, "~/Documents/Github/myddosome_proteomics/data/summaries/PROTEIN_INFO.csv", row.names = F, sep = ",")
```

### READ PROTEIN INFO DF

```{r}
PROTEIN_INFO <- fread("~/Documents/Github/myddosome_proteomics/data/summaries/PROTEIN_INFO.csv") %>% select(1:24)
PROTEIN_INFO <- rename(PROTEIN_INFO, QUERY = protein_id)
```

### MERGE WITH RUN SUMMARY

```{r}
MAIN <- 
  left_join(QUERY_RUN_SUMMARY, PROTEIN_INFO, by = "QUERY") %>% 
  mutate(Confidence = case_when(iScore < 0.4 ~ "Low",
                                iScore >= 0.4 & iScore < 0.5 ~ "Medium",
                                iScore >= 0.5 & iScore < 0.7 ~ "High",
                                TRUE ~ "Very High"),
         Clash_Indicator = iRes/iCnt) %>%
  filter(!is.na(Entry))

MAIN_SUBSET <- MAIN %>% 
  group_by(Entry.Name) %>%
  filter(iScore == max(iScore))

FOLDER = "MYD88"

```

``` {r}

FENJA_SIGNIF_FILTERED <- TIME_CHECK %>% 
  filter((`-LOG(P-value)` > 2) & (Difference > 1) & (Significant == T) & (KO == "NONE"), 
         SIGNIF_CLASS == "SIGNIFICANT")

FENJA_SIGNIF_FILTERED %>%
  ggplot(aes(PULLED_PROTEIN, fill=PULLED_PROTEIN)) +
  geom_bar() +
  facet_grid(~as.factor(ORIGIN), scales = "free_y") +
  theme(legend.position = "none")

# HOW FENJA FILTERED THE PROTEINS
MYD88.cnt <- FENJA_SIGNIF_FILTERED %>% filter(PULLED_PROTEIN == "MYD88") %>% group_by(ORIGIN) %>% count()
# kable(MYD88.cnt, caption = "Filtered Proteins pulled down with MyD88 per time point")

IRAK4.cnt <- FENJA_SIGNIF_FILTERED %>% filter(PULLED_PROTEIN == "IRAK4") %>% group_by(ORIGIN) %>% count()
# kable(IRAK4.cnt, caption = "Filtered Proteins pulled down with IRAK4 per time point")


IRAK1 <- FENJA_SIGNIF_FILTERED %>% filter(PULLED_PROTEIN == "IRAK1") %>% pull(Protein.IDs) %>% unique() %>% as.data.frame()
IRAK1_filtered <- IRAK1 %>% filter(!str_detect(., pattern = "CON__"))
IRAK1_filtered <- unlist(lapply(strsplit(IRAK1_filtered$., ";", fixed=TRUE), function(x) return(x[1]))) %>%
  unique() %>% as.data.frame()

IRAK1.cnt <- FENJA_SIGNIF_FILTERED %>% filter(PULLED_PROTEIN == "IRAK1") %>% group_by(ORIGIN) %>% count()
# kable(IRAK1.cnt, caption = "Filtered Proteins pulled down with IRAK1 per time point")
```

### PLOT ALL

```{r}
MAIN_PLOT <- MAIN %>% group_by(QUERY) %>%
  ggplot(aes(iScore, piTM, label = Entry.Name)) +
  geom_abline(col = "gray") +
  geom_point(aes(col = Confidence), size = 3) +  # Use the new Confidence variable here
  scale_color_manual(name = "Confidence",
                     values = c("Low" = "gray80",
                                "Medium" = "gray40",
                                "High" = "cornflowerblue",
                                "Very High" = "lightgreen")) +
  ggrepel::geom_label_repel(data = MAIN, show.legend = F) +
  ggtitle(paste0('Computational screening for PPI partners of ', FOLDER)) +
  expand_limits(x=c(0,1), y=c(0,1)) +
  geom_vline(xintercept = 0.4, col = "gray40", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.5, col = "cornflowerblue", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.7, col = "lightgreen", linetype = "dotted", linewidth = 1) +
  annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
  annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
  annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence") +
  theme(legend.position = "none")
  
# ggplotly(MAIN_PLOT)
```

### PLOT SUBSET

```{r}
MAIN_SUBSET_PLOT <- MAIN_SUBSET %>% group_by(QUERY) %>%
  ggplot(aes(iScore, piTM, label = Entry.Name)) +
  geom_abline(col = "gray") +
  geom_point(aes(col = Confidence), size = 3) +  # Use the new Confidence variable here
  scale_color_manual(name = "Confidence",
                     values = c("Low" = "gray80",
                                "Medium" = "gray40",
                                "High" = "cornflowerblue",
                                "Very High" = "lightgreen")) +
  ggtitle(paste0('Computational screening for PPI partners of ', FOLDER)) +
  expand_limits(x=c(0,1), y=c(0,1)) +
  geom_vline(xintercept = 0.4, col = "gray40", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.5, col = "cornflowerblue", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.7, col = "lightgreen", linetype = "dotted", linewidth = 1) +
  annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
  annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
  annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence") +
  theme(legend.position = "none")
  
ggplotly(MAIN_SUBSET_PLOT)
```

### PLOT SUBSET WITH ADDITIONAL FILTER FOR CLASH SCORE (size)
``` {r}
MAIN_SUBSET_filtered_for_clash_indicator <- MAIN_SUBSET %>% group_by(QUERY) %>% filter(Clash_Indicator > 0.4)

MAIN_SUBSET_filtered_for_clash_indicator_PLT <- MAIN_SUBSET_filtered_for_clash_indicator %>% 
  group_by(QUERY) %>%
  ggplot(aes(iScore, piTM, label = Entry.Name)) +
  geom_abline(col = "gray") +
  geom_point(aes(col = Confidence, size = Clash_Indicator)) +  # Use the new Confidence variable here
  scale_color_manual(name = "Confidence",
                     values = c("Low" = "gray80",
                                "Medium" = "gray40",
                                "High" = "cornflowerblue",
                                "Very High" = "lightgreen")) +
  ggtitle(paste0('Computational screening for PPI partners of ', FOLDER)) +
  expand_limits(x=c(0,1), y=c(0,1)) +
  geom_vline(xintercept = 0.4, col = "gray40", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.5, col = "cornflowerblue", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.7, col = "lightgreen", linetype = "dotted", linewidth = 1) +
  annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
  annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
  annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence") +
  theme(legend.position = "none")
  
ggplotly(MAIN_SUBSET_filtered_for_clash_indicator_PLT)

```

### CANDIDATES THAT PASS CONFIDENCE THRESHOLD ≥ 0.4

```{r}
unq_protein_ids_above_threshold <- MAIN %>% filter(iScore >=0.4, !is.na(Entry)) %>% pull(QUERY) %>% unique() %>% as.data.frame()

fwrite(unq_protein_ids_above_threshold, "~/Documents/Github/myddosome_proteomics/data/summaries/unq_protein_ids_above_threshold.csv", sep = ",", row.names = F, col.names = F)

unq_protein_ids_above_threshold2 <- MAIN %>% filter(iScore >=0.4, !is.na(Entry)) %>% select(QUERY, Entry.Name, Gene.Names..primary., Function..CC.) %>% unique() %>% as.data.frame()
fwrite(unq_protein_ids_above_threshold2, "~/Documents/Github/myddosome_proteomics/data/summaries/unq_protein_ids_above_threshold_detail.csv", sep = ",", row.names = F, col.names = T, append = F)

unq_protein_ids_high_conf <- MAIN %>% filter(iScore >=0.4, !is.na(Entry), Confidence == "High") %>% select(QUERY, Entry.Name, Gene.Names..primary., Function..CC.) %>% unique() %>% as.data.frame()
fwrite(unq_protein_ids_high_conf, "~/Documents/Github/myddosome_proteomics/data/summaries/unq_protein_ids_high_conf.csv", sep = ",", row.names = F, col.names = T, append = F)

unq_protein_ids_medium_conf <- MAIN %>% filter(iScore >=0.4, !is.na(Entry), Confidence == "Medium") %>% select(QUERY, Entry.Name, Gene.Names..primary., Function..CC.) %>% unique() %>% as.data.frame()
fwrite(unq_protein_ids_medium_conf, "~/Documents/Github/myddosome_proteomics/data/summaries/unq_protein_ids_medium_conf.csv", sep = ",", row.names = F, col.names = T, append = F)

```

### FOLLOW GOOD CANDIDATES WITHOUT RECYCLES

``` {r}
# Convert 'rep' to factor type in MAIN and MAIN_SUBSET
MAIN$rep <- as.factor(MAIN$rep)
MAIN_SUBSET$rep <- as.factor(MAIN_SUBSET$rep)

# Define unique protein IDs above threshold without recycled items
unq_protein_ids_above_threshold <- MAIN %>% 
  filter(iScore >= 0.4, !is.na(Entry), !str_detect(RECYCLE, pattern = "_recycled_")) %>% 
  pull(QUERY) %>% 
  unique() %>% 
  as.data.frame()

# Define unique protein IDs above threshold, full set
unq_protein_ids_above_threshold_FULL <- MAIN %>% 
  group_by(QUERY) %>%
  filter(QUERY %in% unq_protein_ids_above_threshold$.,
         !str_detect(RECYCLE, pattern = "_recycled_"),
         !is.na(Entry)) %>% 
  ungroup() %>%
  mutate(DATE = as.character(as.IDate(DATE)))

# Define unique protein IDs above threshold, subset with max iScore
unq_protein_ids_above_threshold_SUBSET <- MAIN %>% 
  filter(!str_detect(RECYCLE, pattern = "_recycled_"),
         !is.na(Entry)) %>%
  group_by(QUERY) %>%
  filter(QUERY %in% unq_protein_ids_above_threshold$.,
         iScore == max(iScore)) %>%
  ungroup() %>%
  mutate(DIFF_SCORE = max(iScore) - min(iScore),
         DATE = as.character(as.IDate(DATE)))

# Generate the plot
unq_protein_ids_above_threshold_PLOT <- ggplot(data = unq_protein_ids_above_threshold_SUBSET, 
                                              aes(x = iScore, y = piTM, label = Entry.Name)) +
  geom_abline(col = "gray") +
  # geom_encircle(data = unq_protein_ids_above_threshold_FULL, aes(group = QUERY, fill = QUERY), alpha = 0.5, show.legend = F) +
  geom_point(data = unq_protein_ids_above_threshold_FULL, col = "gray40") +
  geom_point(aes(group = QUERY, text = paste("iScore:", iScore, "<br>piTM:", piTM,
                                             "<br>Entry Name:", Entry.Name, "<br>Gene:", Gene.Names..primary.,
                                             "<br>Date:", DATE, "<br>rep:", rep)),
             size = 3, col = "salmon") +
  ggtitle(paste0('Computational screening for PPI partners of ', FOLDER)) +
  expand_limits(x = c(0, 1), y = c(0, 1)) +
  geom_vline(xintercept = 0.4, col = "gray40", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.5, col = "cornflowerblue", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.7, col = "lightgreen", linetype = "dotted", linewidth = 1) +
  annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
  annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
  annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence") +
  theme(legend.position = "bottom") + 
  facet_wrap(~Gene.Names..primary.)

# Show the plot
unq_protein_ids_above_threshold_PLOT

```
``` {r}
iscore_histo <- MAIN %>%
  group_by(QUERY) %>%
  mutate(mean_plddt = mean(pLDDT)) %>%
  filter(Clash_Indicator > 0.4,
         # mean_plddt > 70
         ) %>%
  filter(iScore == max(iScore))

iscore_histo %>%
  ggplot(aes(iScore)) +
  geom_histogram() +
  expand_limits(x=c(0.1,1), y=c(0.1,1))
  

```


```{r, warning=FALSE}
MAIN$rep        <- as.factor(MAIN$rep)
MAIN_SUBSET$rep <- as.factor(MAIN_SUBSET$rep)

# define unq_protein_ids_above_threshold_FULL
unq_protein_ids_above_threshold_FULL <- MAIN %>% 
  group_by(QUERY) %>%
  filter(QUERY %in% unq_protein_ids_above_threshold$.,
         # !str_detect(RECYCLE, pattern = "_recycled_"),
         !is.na(Entry)) %>%
  ungroup(rep) %>%
  mutate(DATE = as.character(as.IDate(DATE)))

# define unq_protein_ids_above_threshold_SUBSET
unq_protein_ids_above_threshold_SUBSET <- MAIN %>% 
  group_by(QUERY) %>%
  filter(QUERY %in% unq_protein_ids_above_threshold$.,
         iScore == max(iScore),
         !is.na(Entry)) %>%
  ungroup(rep) %>%
  mutate(DIFF_SCORE = max(iScore)-min(iScore),
         DATE = as.character(as.IDate(DATE))) %>% 
  filter(DIFF_SCORE < .2)

# plot
unq_protein_ids_above_threshold_PLOT <- unq_protein_ids_above_threshold_SUBSET %>% 
  group_by(QUERY) %>%
  ggplot(aes(iScore, piTM, label = Entry.Name)) +
  geom_abline(col = "gray") +
  geom_encircle(data = unq_protein_ids_above_threshold_FULL,
            aes(group = QUERY, fill = QUERY),
            alpha = 0.5, 
            show.legend = F) +
  geom_point(data = unq_protein_ids_above_threshold_FULL, col = "gray40") +
  geom_point(aes(group = QUERY,
                 text = paste("iScore:", iScore,
                              "<br>piTM:", piTM,
                              "<br>Entry Name:", Entry.Name,
                              "<br>Gene:",Gene.Names..primary.,
                              "<br>Date:", DATE,
                              "<br>rep:", rep)), size = 3, col = "salmon") +
  # scale_color_gradient(low = "red", high = "lightgray") +  # Add this line for the color gradient
  ggtitle(paste0('Computational screening for PPI partners of ', FOLDER)) +
  expand_limits(x=c(0,1), y=c(0,1)) +
  geom_vline(xintercept = 0.4, col = "gray40", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.5, col = "cornflowerblue", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.7, col = "lightgreen", linetype = "dotted", linewidth = 1) +
  annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
  annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
  annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence") +
  theme(legend.position = "bottom") + 
  facet_wrap(~Gene.Names..primary.)

# ggplotly(unq_protein_ids_above_threshold_PLOT, tooltip = "text")
unq_protein_ids_above_threshold_PLOT

ggsave(plot = unq_protein_ids_above_threshold_PLOT,
         filename = paste0("~/Documents/Github/myddosome_proteomics/data/figures/unq_protein_ids_above_threshold_PLOT.svg"),
       scale = 1,
       units = "in",
       height = 24,
       width = 40)
```

### extract plots for proteins of interest

``` {r}

for (ID in unq_protein_ids_above_threshold_SUBSET$FILE) {
  subset_df = MAIN %>%
    filter(FILE == ID,
           !str_detect(RECYCLE, pattern = "_recycled_"))
  
  max_iScore_ID <- MAIN %>%
  filter(FILE == ID,
         !str_detect(RECYCLE, pattern = "_recycled_")) %>%
  group_by(as.factor(DATE)) %>%
  slice_max(order_by = iScore, n = 1) %>%
  ungroup()
  
  
  plt_by_ID <- subset_df %>% 
    ggplot(aes(iScore, piTM, label = Entry.Name)) +
    geom_abline(col = "gray") +
    geom_line(data = subset_df,
            aes(group = as.factor(DATE), 
                col = as.factor(DATE)),
            alpha = 0.5, 
            show.legend = F) +
    geom_point(data = subset_df, size = 3,
             aes(col = as.factor(DATE)),
             alpha = 0.5, 
             show.legend = F) +
    geom_point(data = max_iScore_ID, 
             aes(fill = as.factor(DATE)), 
             col = "black",
             size = 4, shape = 21) +
  ggtitle(paste0('Computational screening of MYD88 vs. ', unique(subset_df$Entry.Name))) +
  expand_limits(x=c(0,1), y=c(0,1)) +
  geom_vline(xintercept = 0.4, col = "gray40", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.5, col = "cornflowerblue", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.7, col = "lightgreen", linetype = "dotted", linewidth = 1) +
  annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
  annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
  annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence") +
  theme(legend.position = "bottom") +
  labs(fill = "DATE")  # Setting the legend title for the fill aesthetic
  
  plt_by_ID

  ggsave(plot = plt_by_ID,
         filename = paste0("~/Documents/Github/myddosome_proteomics/data/figures/",ID,".svg"),
       scale = 1,
       units = "in",
       height = 6,
       width = 10)
}


```

``` {r}
for (ID in unq_protein_ids_above_threshold_SUBSET$FILE) {
  subset_df = MAIN %>%
    filter(FILE == ID)
  
  max_iScore_ID <- MAIN %>%
  filter(FILE == ID) %>%
  group_by(as.factor(DATE)) %>%
  slice_max(order_by = iScore, n = 1) %>%
  ungroup()
  
  
  plt_by_ID <- subset_df %>% 
    ggplot(aes(iScore, piTM, label = Entry.Name)) +
    geom_abline(col = "gray") +
    geom_encircle(data = subset_df,
            aes(group = as.factor(DATE), 
                fill = as.factor(DATE)),
            alpha = 0.1, 
            show.legend = F) +
    geom_point(data = subset_df, size = 3,
             aes(col = as.factor(DATE)),
             alpha = 0.5, 
             show.legend = F) +
    geom_point(data = max_iScore_ID, 
             aes(fill = as.factor(DATE)), 
             col = "black",
             size = 4, shape = 21) +
  ggtitle(paste0('Computational screening of MYD88 vs. ', unique(subset_df$Entry.Name))) +
  expand_limits(x=c(0,1), y=c(0,1)) +
  geom_vline(xintercept = 0.4, col = "gray40", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.5, col = "cornflowerblue", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.7, col = "lightgreen", linetype = "dotted", linewidth = 1) +
  annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
  annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
  annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence") +
  theme(legend.position = "bottom") +
  labs(fill = "DATE")  # Setting the legend title for the fill aesthetic
  
  plt_by_ID

  ggsave(plot = plt_by_ID,
         filename = paste0("~/Documents/Github/myddosome_proteomics/data/figures/",ID,"_FULL.svg"),
       scale = 1,
       units = "in",
       height = 6,
       width = 10)
}
```

``` {r}
for (ID in unq_protein_ids_above_threshold_SUBSET$FILE) {
  subset_df = MAIN %>%
    filter(FILE == ID)
  
  max_iScore_ID <- MAIN %>%
  filter(FILE == ID) %>%
  group_by(as.factor(DATE)) %>%
  slice_max(order_by = iScore, n = 1) %>%
  ungroup()
  
  
  plt_by_ID <- subset_df %>% 
    ggplot(aes(iScore, piTM, label = Entry.Name)) +
    geom_abline(col = "gray") +
    geom_point(data = subset_df, size = 2, aes(col = as.factor(DATE)), alpha = 0.3,  show.legend = F) +
    geom_point(data = max_iScore_ID, aes(fill = as.factor(DATE)), col = "black", size = 4, shape = 21) +
    geom_density_2d(data = subset_df, show.legend = F, alpha = 0.5) +
    ggtitle(paste0('Computational screening of MYD88 vs. ', unique(subset_df$Entry.Name))) +
    expand_limits(x=c(0,1), y=c(0,1)) +
    geom_vline(xintercept = 0.4, col = "gray40", linetype = "dotted", linewidth = 1) +
    geom_vline(xintercept = 0.5, col = "cornflowerblue", linetype = "dotted", linewidth = 1) +
    geom_vline(xintercept = 0.7, col = "lightgreen", linetype = "dotted", linewidth = 1) +
    annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
    annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
    annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence") +
    theme(legend.position = "bottom") +
    labs(fill = "DATE")  # Setting the legend title for the fill aesthetic
  
  plt_by_ID

  ggsave(plot = plt_by_ID,
         filename = paste0("~/Documents/Github/myddosome_proteomics/data/figures/",ID,"_DENSITY.svg"),
       scale = 1,
       units = "in",
       height = 6,
       width = 10)
}
```

### Plot Tubulin

```{r}

ID = "MYD88_MOUSE_x1_P68373_x1"

subset_df = MAIN %>%
    filter(FILE == ID,
           !str_detect(RECYCLE, pattern = "_recycled_"))
  
max_iScore_ID <- MAIN %>%
  filter(FILE == ID, !str_detect(RECYCLE, "_recycled_")) %>%
  group_by(as.factor(rep)) %>%
  slice_max(order_by = iScore, n = 1) %>%
  ungroup()
  
  
plt_by_ID <- subset_df %>% 
    ggplot(aes(iScore, piTM, label = Entry.Name)) +
    geom_abline(col = "gray") +
    geom_line(data = subset_df,
            aes(group = as.factor(rep), 
                col = as.factor(rep)),
            alpha = 0.5, 
            show.legend = F) +
    geom_point(data = subset_df, size = 3,
             aes(col = as.factor(rep)),
             alpha = 0.5, 
             show.legend = F) +
    geom_point(data = max_iScore_ID, 
             aes(fill = as.factor(rep)), 
             col = "black",
             size = 4, shape = 21) +
  ggtitle(paste0('Computational screening of MYD88 vs. ', unique(subset_df$Entry.Name))) +
  expand_limits(x=c(0,1), y=c(0,1)) +
  geom_vline(xintercept = 0.4, col = "gray40", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.5, col = "cornflowerblue", linetype = "dotted", linewidth = 1) +
  geom_vline(xintercept = 0.7, col = "lightgreen", linetype = "dotted", linewidth = 1) +
  annotate("text", x = 0.4, y = -0.05, label = "medium \n confidence") +
  annotate("text", x = 0.5, y = -0.05, label = "high \n confidence") +
  annotate("text", x = 0.7, y = -0.05, label = "very high \n confidence") +
  theme(legend.position = "0") +
  labs(fill = "rep")  # Setting the legend title for the fill aesthetic
  
plt_by_ID

ggsave(plot = plt_by_ID,
         filename = paste0("~/Documents/Github/myddosome_proteomics/data/figures/",ID,".svg"),
       scale = 1,
       units = "in",
       height = 6,
       width = 10)
```

```{r}
library(dplyr)

# Calculate the proportion of models with pLDDT > 70 for each protein
proportion_over_70_long <- MAIN %>%
  group_by(QUERY) %>%
  summarise(proportion_above_70 = round(mean(pLDDT > 70), 2),
            mean_pLDDT = round(mean(pLDDT), 2),
            pLDDT = pLDDT) %>%
  ungroup()

proportion_over_70 <- MAIN %>%
  group_by(QUERY) %>%
  summarise(proportion_above_70 = round(mean(pLDDT > 70), 2),
            mean_pLDDT = round(mean(pLDDT), 2)) %>%
  distinct(QUERY, .keep_all = T) %>%
  ungroup()

# Set a threshold for the proportion, e.g., 0.6 (meaning at least 60% of models have pLDDT > 70)
threshold <- 0.99

# Filter proteins based on the threshold
potential_rescue_proteins <- proportion_over_70 %>%
  filter(proportion_above_70 >= threshold)

# Join with BDLD_LIB for ELISA_STATUS and other info
candidates_incl_tested <- left_join(potential_rescue_proteins, 
                                    MAIN[,c("QUERY", "iScore", "ELISA_STATUS")],
                                    by = c("QUERY", "ELISA_STATUS"))

# Filter the original bdld dataframe
candidates <- bdld %>%
  filter(ID %in% candidates_incl_tested$ID) %>% arrange(ELISA_STATUS)
# fwrite(candidates_incl_tested, "~/Documents/Github/master_thesis/ESSENTIAL/pLDDT_prop_99_candidates.csv", row.names = F)

kable(candidates_incl_tested)

# All unique IDs from the original dataset
all_ids <- unique(bdld$ID)
# IDs from the potential_rescue_proteins dataset
rescue_ids <- potential_rescue_proteins$ID
# IDs that are filtered OUT
filtered_out_ids <- setdiff(all_ids, rescue_ids)


# Join proportion_over_70 dataframe with BDLD_LIB for the desired columns
filtered_out_df <- proportion_over_70 %>%
  left_join(BDLD_LIB[,c("ID", "taxend", "ELISA_STATUS")], by = c("ID", "ELISA_STATUS")) %>%
  filter(ID %in% filtered_out_ids)
# fwrite(filtered_out_df, "~/Documents/Github/master_thesis/ESSENTIAL/pLDDT_prop_99_eliminated_candidates.csv", row.names = F)

proportion_over_70_long %>%
  ggplot(aes(pLDDT, ELISA_STATUS, col = ELISA_STATUS, alpha = proportion_above_70)) +
  geom_jitter() +
  color_palette(palette = Okabe_Ito)

proportion_over_70_long_plt <- proportion_over_70_long %>%
  ggplot() +
  geom_vline(xintercept = 70, linetype = "dotted") +
  geom_jitter(data = proportion_over_70_long, 
              aes(pLDDT, ELISA_STATUS), 
              alpha = 0.1) +
  geom_point(data = filtered_out_df, 
             aes(mean_pLDDT, ELISA_STATUS, shape = ID %in% ORDERED,
                 size = proportion_above_70), 
             col = "black", 
             alpha = 0.8,
             fill = "#56B4E9",
             position = position_jitterdodge(jitter.width = 0.3, dodge.width = 0.8)) +
  geom_point(data = potential_rescue_proteins, 
             aes(mean_pLDDT, ELISA_STATUS, shape = ID %in% ORDERED,
                 size = proportion_above_70),
             col = "black",
             fill = "#E69F00",
             alpha = 0.8,
             position = position_jitterdodge(jitter.width = 0.3, dodge.width = 0.8)) +
  scale_shape_manual(values = c(21, 24)) +  # Here, shape 1 (circle) for FALSE and shape 2 (triangle) for TRUE
  expand_limits(x=0, y=0) +
  labs(y = "Rescue Ability") +
  theme_cowplot(font_size = 20) +
  # theme(legend.position = 0) +
  scale_x_continuous(breaks = c(0, 50, 70, 100))

proportion_over_70_long_plt

ggsave(plot = proportion_over_70_long_plt, filename = paste0(save_to,"/Figure_proportion_over_70_long.svg"),
       scale = 1,
       units = "in",
       height = 6,
       width = 10)

```

### Check out pDockQ

```{r}
MAIN <- MAIN %>%
  group_by(QUERY) %>%
  mutate(pDockQ = 0.707/1+exp(1))
```
